# ------------------------
# FastAPI Application Configuration
# ------------------------
# This file contains settings for the FastAPI server.
# ------------------------
title: "Taxi Data Analytics API"
description: "An API to serve analytics results from the taxi trip data."
version: "1.0.0"
host: "0.0.0.0"
port: 8000
reload: true